04/09/2025 17:25:23 - INFO     - --------------------------------------------------
04/09/2025 17:25:23 - INFO     - Lancement Application                           
04/09/2025 17:25:23 - INFO     - --------------------------------------------------
04/09/2025 17:25:23 - INFO     - AccueilVue
04/09/2025 18:58:33 - INFO     - --------------------------------------------------
04/09/2025 18:58:33 - INFO     - Lancement Webservice                           
04/09/2025 18:58:33 - INFO     - --------------------------------------------------
04/09/2025 18:58:53 - INFO     - Arret du Webservice
04/09/2025 19:03:02 - INFO     - --------------------------------------------------
04/09/2025 19:03:02 - INFO     - Lancement Application                           
04/09/2025 19:03:02 - INFO     - --------------------------------------------------
04/09/2025 19:03:02 - INFO     - AccueilVue
04/09/2025 19:03:10 - INFO     - InscriptionVue
04/09/2025 19:03:25 - INFO     -     UtilisateurService.mail_deja_utilise('felicia.dossou@sfr.fr',) - DEBUT
04/09/2025 19:03:25 - INFO     -         UtilisateurDao.lister_tous() - DEBUT
04/09/2025 19:03:25 - INFO     - 'utf-8' codec can't decode byte 0xf4 in position 72: invalid continuation byte
04/09/2025 19:03:25 - ERROR    - UnicodeDecodeError : 'utf-8' codec can't decode byte 0xf4 in position 72: invalid continuation byte
Traceback (most recent call last):
  File "C:\Users\PC\OneDrive\Documents\ensai\projet info\ensai-gpt\src\main.py", line 28, in <module>
    vue_courante = vue_courante.choisir_menu()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\OneDrive\Documents\ensai\projet info\ensai-gpt\src\view\accueil\inscription_vue.py", line 20, in choisir_menu
    if UtilisateurService().mail_deja_utilise(mail):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\OneDrive\Documents\ensai\projet info\ensai-gpt\src\utils\log_decorator.py", line 61, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\OneDrive\Documents\ensai\projet info\ensai-gpt\src\service\utilisateur_service.py", line 94, in mail_deja_utilise
    utilisateurs = UtilisateurDao().lister_tous()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\OneDrive\Documents\ensai\projet info\ensai-gpt\src\utils\log_decorator.py", line 61, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\OneDrive\Documents\ensai\projet info\ensai-gpt\src\dao\utilisateur_dao.py", line 72, in lister_tous
    with DBConnection().connection as connection:
         ^^^^^^^^^^^^^^
  File "C:\Users\PC\OneDrive\Documents\ensai\projet info\ensai-gpt\src\utils\singleton.py", line 11, in __call__
    instance = super().__call__(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\OneDrive\Documents\ensai\projet info\ensai-gpt\src\dao\db_connection.py", line 19, in __init__
    self.__connection = psycopg2.connect(
                        ^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\Miniconda3\envs\ensai-gpt\Lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf4 in position 72: invalid continuation byte
04/09/2025 19:03:25 - INFO     - AccueilVue
04/09/2025 19:03:28 - INFO     - ConnexionVue
04/09/2025 19:03:37 - INFO     -             UtilisateurService.se_connecter('felicia.dossou@sfr.fr', '*****') - DEBUT
04/09/2025 19:03:37 - INFO     -                 UtilisateurDao.se_connecter('felicia.dossou@sfr.fr', '*****') - DEBUT
04/09/2025 19:03:37 - INFO     - 'utf-8' codec can't decode byte 0xf4 in position 72: invalid continuation byte
04/09/2025 19:03:37 - INFO     -                 UtilisateurDao.se_connecter('felicia.dossou@sfr.fr', '*****') - FIN
04/09/2025 19:03:37 - INFO     -                    └─> Sortie : None
04/09/2025 19:03:37 - INFO     -             UtilisateurService.se_connecter('felicia.dossou@sfr.fr', '*****') - FIN
04/09/2025 19:03:37 - INFO     -                └─> Sortie : None
04/09/2025 19:03:37 - INFO     - AccueilVue
04/09/2025 19:03:42 - INFO     - AccueilVue
04/09/2025 19:03:52 - INFO     - Fin de l'application
04/09/2025 19:04:29 - INFO     - --------------------------------------------------
04/09/2025 19:04:29 - INFO     - Lancement Application                           
04/09/2025 19:04:29 - INFO     - --------------------------------------------------
04/09/2025 19:04:29 - INFO     - AccueilVue
04/09/2025 19:04:31 - INFO     - InscriptionVue
04/09/2025 19:04:43 - INFO     -     UtilisateurService.mail_deja_utilise('felicia.dossou@sfr.fr',) - DEBUT
04/09/2025 19:04:43 - INFO     -         UtilisateurDao.lister_tous() - DEBUT
04/09/2025 19:04:43 - INFO     - 'utf-8' codec can't decode byte 0xf4 in position 72: invalid continuation byte
04/09/2025 19:04:43 - ERROR    - UnicodeDecodeError : 'utf-8' codec can't decode byte 0xf4 in position 72: invalid continuation byte
Traceback (most recent call last):
  File "C:\Users\PC\OneDrive\Documents\ensai\projet info\ensai-gpt\src\main.py", line 28, in <module>
    vue_courante = vue_courante.choisir_menu()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\OneDrive\Documents\ensai\projet info\ensai-gpt\src\view\accueil\inscription_vue.py", line 20, in choisir_menu
    if UtilisateurService().mail_deja_utilise(mail):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\OneDrive\Documents\ensai\projet info\ensai-gpt\src\utils\log_decorator.py", line 61, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\OneDrive\Documents\ensai\projet info\ensai-gpt\src\service\utilisateur_service.py", line 94, in mail_deja_utilise
    utilisateurs = UtilisateurDao().lister_tous()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\OneDrive\Documents\ensai\projet info\ensai-gpt\src\utils\log_decorator.py", line 61, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\OneDrive\Documents\ensai\projet info\ensai-gpt\src\dao\utilisateur_dao.py", line 72, in lister_tous
    with DBConnection().connection as connection:
         ^^^^^^^^^^^^^^
  File "C:\Users\PC\OneDrive\Documents\ensai\projet info\ensai-gpt\src\utils\singleton.py", line 11, in __call__
    instance = super().__call__(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\OneDrive\Documents\ensai\projet info\ensai-gpt\src\dao\db_connection.py", line 19, in __init__
    self.__connection = psycopg2.connect(
                        ^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\Miniconda3\envs\ensai-gpt\Lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf4 in position 72: invalid continuation byte
04/09/2025 19:04:43 - INFO     - AccueilVue
04/09/2025 19:04:47 - INFO     - Fin de l'application
